name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Kiểm tra tất cả các nhánh
  pull_request:
    branches:
      - '**'  # Kiểm tra tất cả các pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Run tests
      run: go test -v ./...

    - name: Build Docker image
      run: docker build -t my-go-app .

    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker push my-go-app
